FROM node:24.11.1

WORKDIR /app/client

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/a376818/nodejs-tcp.git .

RUN cd client && npm install

EXPOSE 4000

CMD ["node", "client/client.js"]